import type { AppState } from '../types';

export const defaultAppState: AppState = {
  cards: [
    {
      id: 'card-1',
      name: 'Ziraat Bankkart',
      type: 'debit',
      bank: 'Ziraat Bankası',
      lastFour: '1234',
      balance: 2500.0,
      color: '#1B5E20',
      isActive: true,
    },
    {
      id: 'card-2',
      name: 'KYK Kart',
      type: 'kyk',
      bank: 'KYK',
      lastFour: '5678',
      balance: 850.0,
      color: '#1565C0',
      isActive: true,
    },
    {
      id: 'card-3',
      name: 'Bankkart Kredi',
      type: 'credit',
      bank: 'Ziraat Bankası',
      lastFour: '9012',
      balance: -320.5,
      color: '#4A148C',
      isActive: true,
    },
    {
      id: 'card-4',
      name: 'Multinet',
      type: 'prepaid',
      bank: 'Multinet',
      lastFour: '3456',
      balance: 450.0,
      color: '#E65100',
      isActive: true,
    },
    {
      id: 'card-5',
      name: 'Papara',
      type: 'prepaid',
      bank: 'Papara',
      lastFour: '7890',
      balance: 1200.75,
      color: '#880E4F',
      isActive: true,
    },
  ],
  categories: [
    {
      id: 'cat-1',
      name: 'Yiyecek & İçecek',
      icon: '🍕',
      color: '#FF6B6B',
      subcategories: [
        { id: 'sub-1-1', name: 'Restoran' },
        { id: 'sub-1-2', name: 'Market' },
        { id: 'sub-1-3', name: 'Kafe' },
        { id: 'sub-1-4', name: 'Fast Food' },
      ],
    },
    {
      id: 'cat-2',
      name: 'Ulaşım',
      icon: '🚌',
      color: '#4ECDC4',
      subcategories: [
        { id: 'sub-2-1', name: 'Otobüs / Metro' },
        { id: 'sub-2-2', name: 'Taksi' },
        { id: 'sub-2-3', name: 'Yakıt' },
        { id: 'sub-2-4', name: 'Park' },
      ],
    },
    {
      id: 'cat-3',
      name: 'Eğitim',
      icon: '📚',
      color: '#45B7D1',
      subcategories: [
        { id: 'sub-3-1', name: 'Kitap' },
        { id: 'sub-3-2', name: 'Kırtasiye' },
        { id: 'sub-3-3', name: 'Kurs' },
      ],
    },
    {
      id: 'cat-4',
      name: 'Giyim',
      icon: '👕',
      color: '#96CEB4',
      subcategories: [
        { id: 'sub-4-1', name: 'Üst Giyim' },
        { id: 'sub-4-2', name: 'Ayakkabı' },
        { id: 'sub-4-3', name: 'Aksesuar' },
      ],
    },
    {
      id: 'cat-5',
      name: 'Eğlence',
      icon: '🎮',
      color: '#FFEAA7',
      subcategories: [
        { id: 'sub-5-1', name: 'Sinema' },
        { id: 'sub-5-2', name: 'Oyun' },
        { id: 'sub-5-3', name: 'Müzik' },
        { id: 'sub-5-4', name: 'Spor' },
      ],
    },
    {
      id: 'cat-6',
      name: 'Sağlık',
      icon: '💊',
      color: '#FF7675',
      subcategories: [
        { id: 'sub-6-1', name: 'Eczane' },
        { id: 'sub-6-2', name: 'Doktor' },
        { id: 'sub-6-3', name: 'Spor Salonu' },
      ],
    },
    {
      id: 'cat-7',
      name: 'Faturalar',
      icon: '📄',
      color: '#74B9FF',
      subcategories: [
        { id: 'sub-7-1', name: 'Elektrik' },
        { id: 'sub-7-2', name: 'Su' },
        { id: 'sub-7-3', name: 'Doğalgaz' },
        { id: 'sub-7-4', name: 'İnternet' },
        { id: 'sub-7-5', name: 'Telefon' },
      ],
    },
    {
      id: 'cat-8',
      name: 'Diğer',
      icon: '💼',
      color: '#A29BFE',
      subcategories: [{ id: 'sub-8-1', name: 'Diğer' }],
    },
  ],
  incomeCategories: [
    { id: 'inc-1', name: 'Maaş', icon: '💼', color: '#00B894' },
    { id: 'inc-2', name: 'Burs', icon: '🎓', color: '#0984E3' },
    { id: 'inc-3', name: 'Freelance', icon: '💻', color: '#6C5CE7' },
    { id: 'inc-4', name: 'Hediye', icon: '🎁', color: '#FDCB6E' },
    { id: 'inc-5', name: 'Yatırım', icon: '📈', color: '#E17055' },
    { id: 'inc-6', name: 'Diğer', icon: '💰', color: '#81ECEC' },
  ],
  expenses: [
    {
      id: 'exp-1',
      cardId: 'card-1',
      categoryId: 'cat-1',
      subcategoryId: 'sub-1-2',
      location: 'Migros',
      amount: 185.5,
      description: 'Haftalık market alışverişi',
      regret: false,
      date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-2',
      cardId: 'card-2',
      categoryId: 'cat-2',
      subcategoryId: 'sub-2-1',
      location: 'İETT',
      amount: 25.0,
      description: '',
      regret: false,
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-3',
      cardId: 'card-4',
      categoryId: 'cat-1',
      subcategoryId: 'sub-1-3',
      location: 'Starbucks',
      amount: 75.0,
      description: 'Arkadaşlarla buluşma',
      regret: true,
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-4',
      cardId: 'card-1',
      categoryId: 'cat-3',
      subcategoryId: 'sub-3-1',
      location: 'D&R',
      amount: 120.0,
      description: 'Ders kitabı',
      regret: false,
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-5',
      cardId: 'card-5',
      categoryId: 'cat-5',
      subcategoryId: 'sub-5-1',
      location: 'Cinemaximum',
      amount: 95.0,
      description: '',
      regret: false,
      date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-6',
      cardId: 'card-1',
      categoryId: 'cat-1',
      subcategoryId: 'sub-1-4',
      location: 'Burger King',
      amount: 89.0,
      description: '',
      regret: true,
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-7',
      cardId: 'card-3',
      categoryId: 'cat-7',
      subcategoryId: 'sub-7-4',
      location: 'Turkcell',
      amount: 299.0,
      description: 'Aylık internet faturası',
      regret: false,
      date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-8',
      cardId: 'card-1',
      categoryId: 'cat-4',
      subcategoryId: 'sub-4-1',
      location: 'Zara',
      amount: 350.0,
      description: '',
      regret: false,
      date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-9',
      cardId: 'card-2',
      categoryId: 'cat-6',
      subcategoryId: 'sub-6-1',
      location: 'Eczacıbaşı Eczanesi',
      amount: 45.0,
      description: '',
      regret: false,
      date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'exp-10',
      cardId: 'card-5',
      categoryId: 'cat-1',
      subcategoryId: 'sub-1-1',
      location: 'İstanbul Steak House',
      amount: 420.0,
      description: 'Akşam yemeği',
      regret: false,
      date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  incomes: [
    {
      id: 'inc-tx-1',
      accountId: 'card-1',
      amount: 5000.0,
      categoryId: 'inc-1',
      sender: 'KFU Üniversitesi',
      description: 'Aylık maaş',
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'inc-tx-2',
      accountId: 'card-2',
      amount: 1400.0,
      categoryId: 'inc-2',
      sender: 'KYK',
      description: 'Aylık burs',
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'inc-tx-3',
      accountId: 'card-5',
      amount: 800.0,
      categoryId: 'inc-3',
      sender: 'Freelance Müşteri',
      description: 'Web projesi ödemesi',
      date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  profile: {
    name: 'Kullanıcı',
    surname: 'KFU',
    photo: undefined,
  },
  gamification: {
    xp: 90,
    streak: 1,
    longestStreak: 1,
    lastActiveDate: new Date().toISOString().slice(0, 10),
    earnedBadgeIds: ['first_expense', 'first_income'],
    totalExpensesAdded: 10,
    totalIncomesAdded: 3,
  },
  goals: [
    {
      id: 'goal-1',
      name: 'Tatil Fonu',
      icon: '✈️',
      type: 'saving',
      targetAmount: 5000,
      currentAmount: 1200,
      deadline: new Date(new Date().setMonth(new Date().getMonth() + 4)).toISOString(),
      isCompleted: false,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'goal-2',
      name: 'Aylık Kafe Limiti',
      icon: '☕',
      type: 'spending_limit',
      targetAmount: 200,
      currentAmount: 75,
      categoryId: 'cat-1',
      isCompleted: false,
      createdAt: new Date().toISOString(),
    },
  ],
  creditInstallments: [
    {
      id: 'inst-1',
      cardId: 'card-3',
      description: 'iPhone 15 Pro',
      totalAmount: 45000,
      installmentCount: 12,
      paidInstallments: 3,
      monthlyAmount: 3750,
      startDate: new Date(new Date().setMonth(new Date().getMonth() - 3)).toISOString(),
    },
  ],
};
